name: artifact
on: [push]
env: 
  FILE_NAME: hello-server
jobs:
  build:
    name: build for linux and windows
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4.2.2
    - name: Display 1
      run: ls -lrt 
    - name: build ${{env.FILE_NAME}} for linux
      run: go build ${{ env.FILE_NAME }}.go
    - name: build ${{env.FILE_NAME}} for windows 
      run: GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go
    - name: Display 2
      run: ls -lrt 
    - name: upload linux
      uses: actions/upload-artifact@v4.6.2
      with:
        name: linux
        path: ${{ env.FILE_NAME }}
        retention-days: 5
        compression-level: 6
        overwrite: false
    - name: upload windows
      uses: actions/upload-artifact@v4.6.2
      with:
        name: windows
        path: ${{ env.FILE_NAME }}.exe
        retention-days: 5
        compression-level: 6
        overwrite: false

  test-linux:
    name: Test Linux
    runs-on: [ubuntu-latest]
    needs: [build]
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: linux

    - name: Test ${{ env.FILE_NAME }}
      run: source ./test.sh

  test-windows:
    name: Test Windows
    runs-on: [windows-latest]
    needs: [build]
    steps:

    - name: Check out code
      uses: actions/checkout@v1

    - name: Download artifact
      uses: actions/download-artifact@v1.0.0
      with:
        name: windows
        
    - name: Test ${{ env.FILE_NAME }}
      run: windows/${{ env.FILE_NAME }}.exe
