# This is a basic workflow to help you get started with Actions

name: date-demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-ub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print date
        run: date +"%Y%M%d %H%m"
