# This is a basic workflow to help you get started with Actions

name: date-demo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job-ub1:
    needs: job-mac
    runs-on: ubuntu-latest
    steps:
      - name: Print date
        run: |
          echo Displaying Date
          date +"%Y%M%d %H%m"
  job-win:
    needs: [job-ub1]
    runs-on: windows-latest
    steps:
      - name: Print date
        run: |
          echo Displaying Date
          Get-Date -Format "yyyyMMdd HHmmK"
  job-mac:
    runs-on: macos-latest
    steps:
      - name: Print date
        run: |
          echo Displaying Date
          date +"%Y%M%d %H%m"
  job-ub2:
    needs: [job-ub1, job-win, job-mac]
    runs-on: ubuntu-latest
    steps:
      - name: Last step
        run: echo Last

                    
